[package]
name = "iociso"
version = "0.1.0"
edition = "2021"

[features]
default = ["iso3166", "isocountry"]
isocountry = ["dep:isocountry"]
iso3166 = ["dep:iso3166"]

[dependencies]
isocountry = { version = "0.3.2", optional = true }
iso3166 = { version = "1.0.1", optional = true }
