[package]
name = "iocisofifa"
version = "0.1.0"
edition = "2021"

[features]
default = []
serde = ["dep:serde"]
std = []

[dependencies]
serde = { version = "1.0", default-features = false, optional = true }
